---

# Uninstall packages stack
- include: playbooks/installation/uninstall_packages.yml


# Reset invaders
- include: playbooks/master_reset_invaders.yml


# Run all port provisioning test cases
- include: playbooks/port_provision/100g_cr_fec_cl91_autoneg_off_lanes_4_count_1.yml

- include: playbooks/port_provision/10g_cr_fec_cl74_autoneg_off_lanes_1_count_4.yml

- include: playbooks/port_provision/10g_cr_fec_none_autoneg_off_lanes_1_count_4.yml

- include: playbooks/port_provision/20g_cr_fec_cl74_autoneg_off_lanes_1_count_4.yml

- include: playbooks/port_provision/20g_cr_fec_none_autoneg_off_lanes_1_count_4.yml

- include: playbooks/port_provision/25g_cr_fec_cl74_autoneg_off_lanes_1_count_4.yml

- include: playbooks/port_provision/25g_cr_fec_none_autoneg_off_lanes_1_count_4.yml

- include: playbooks/port_provision/40g_cr_fec_cl74_autoneg_off_lanes_4_count_1.yml

- include: playbooks/port_provision/40g_cr_fec_none_autoneg_off_lanes_4_count_1.yml

- include: playbooks/port_provision/50g_cr_fec_cl74_autoneg_off_lanes_2_count_2.yml

- include: playbooks/port_provision/50g_cr_fec_none_autoneg_off_lanes_2_count_2.yml

