---
- hosts: server_emulator
  become: true
  ignore_errors: yes
  tasks:
    - file:
        path: "{{ regression_summary_report }}"
        state: absent

    - file:
        path: "{{ regression_summary_report }}"
        state: touch


# Upgrade invaders to latest goes from /home/mpleso/platinabot
#- include: playbooks/upgrade_invaders_to_latest_goes.yml


# Reset invaders to default state
#- include: playbooks/reset_invaders_to_default.yml


# Reset invaders to default state
- include: playbooks/master_reset_invaders.yml


# Run all quagga test cases
- include: quagga_main.yml


# Run all frr test cases
- include: frr_main.yml


# Run all gobgp test cases
- include: gobgp_main.yml


# Run all bird test cases
- include: bird_main.yml


# Run all port provision test cases
- include: port_provision_main.yml


# Run all docker test cases
- include: docker_main.yml


# Run all vlan test cases
- include: vlan_main.yml


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the summary report
      shell: cat "{{ regression_summary_report }}"
      register: summary_report

    - name: Print summary report
      debug:
        var: summary_report.stdout_lines

    - name: Check summary report for failure
      fail:
        msg: "Weekly Regression Failed"
      when: summary_report.stdout.find('Failed') != -1
